In [155]:
import numpy as np

### Important Note

An array can be of Dimension 0, 1, 2...

0-D = has one element only
1-D = always has elements in a squared bracked ([])
2-D = always has elements in double squared bracked ([[]])

### Numpy Arrays

In [156]:
## 0-D array
arr = np.array (1)

arr
print ("shape: ", arr.shape)
print("Array: ", arr)
print ("Dimension: ", arr.ndim)

shape:  ()
Array:  1
Dimension:  0


In [157]:
## 1-D array
arr = np.array ([1, 2, 3, 4])

arr
print ("shape: ", arr.shape)
print("Array: ", arr)
print ("Dimension: ", arr.ndim)

shape:  (4,)
Array:  [1 2 3 4]
Dimension:  1


In [158]:
## 2-D array
arr = np.array ([[1, 2, 3, 4], [1, 2, 3, 4]])

arr
print ("shape: ", arr.shape)
print("Array: ", arr)
print ("Dimension: ", arr.ndim)

shape:  (2, 4)
Array:  [[1 2 3 4]
 [1 2 3 4]]
Dimension:  2


In [161]:
print (str(arr[:, 2]))

[3 3]


In [162]:
## 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([#1D 
                    [#2D
                        [1, 2, 3], [4, 5, 6] #3D 
                    ], 
                    [#2D
                        [7, 8, 9], [10, 11, 12] #3D 
                    ]
            ])

arr
print ("shape: ", arr.shape)
print("Array: ", arr)
print ("Dimension: ", arr.ndim)

shape:  (2, 2, 3)
Array:  [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension:  3


In [164]:
print (str(arr[:, 1]))

[[ 4  5  6]
 [10 11 12]]


In [107]:
# create ndim array, feel free to change ndim below
arr = np.array([1, 2, 3, 4], ndmin=5)

arr
print ("shape: ", arr.shape)
print("Array: ", arr)
print ("Dimension: ", arr.ndim)

shape:  (1, 1, 1, 1, 4)
Array:  [[[[[1 2 3 4]]]]]
Dimension:  5


In [108]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

arr
print ("shape: ", arr.shape)
print("Array: ", arr)
print ("Dimension: ", arr.ndim)

shape:  (15,)
Array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Dimension:  1


In [109]:
arr1 = arr.reshape (3, 5)

arr1
print ("shape: ", arr1.shape)
print("Array: ", arr1)
print ("Dimension: ", arr1.ndim)

shape:  (3, 5)
Array:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimension:  2


In [110]:
a = np.array(1, dtype=float)

a
print ("shape: ", a.shape)
print("Array: ", a)
print ("Dimension: ", a.ndim)

shape:  ()
Array:  1.0
Dimension:  0


In [111]:
## 2-D array
arr = np.array ([[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]])

arr
print ("shape: ", arr.shape)
print("Array: ", arr)
print ("Dimension: ", arr.ndim)

shape:  (3, 4)
Array:  [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
Dimension:  2


In [112]:
# how to create 2-D array
# here the reshape specifies (2 rows, each of 2 rows has 3 sub rows, each of 3 sub row has 4 columns each)
c = np.arange(24).reshape(2, 3, 4)  # 3d array
c
print ("shape: ", c.shape)
print("Array: ", c)
print ("Dimension: ", c.ndim)

shape:  (2, 3, 4)
Array:  [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Dimension:  3


In [113]:
a = np.arange (10000)
b = a.reshape (100, 100)

print (a)
print ("dim: ", a.ndim)
print ("-----------------------")
print (b)
print ("dim: ", b.ndim)

[   0    1    2 ... 9997 9998 9999]
dim:  1
-----------------------
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]
dim:  2


In [114]:
a = np.array([20, 30, 40, 50])
b = np.arange(4) # arange will create a 1-D array
c = np.array(4) # array will create a 0-D array

print (a)
print ("A dim: ", a.ndim)
print ("-----------------------")
print (b)
print ("B dim: ", b.ndim)
print ("-----------------------")
print (c)
print ("C dim: ", c.ndim)

[20 30 40 50]
A dim:  1
-----------------------
[0 1 2 3]
B dim:  1
-----------------------
4
C dim:  0


### Numpy Matrices

In [115]:
a = np.matrix('1 2; 3 4') 
a
print ("shape: ", a.shape)
print("Array: ", a)
print ("Dimension: ", a.ndim)

shape:  (2, 2)
Array:  [[1 2]
 [3 4]]
Dimension:  2


### Numpy List to Matrices

In [118]:
list1 = [1, 2, 3] 
list1 = np.array (list1)
print ("Shape: ", list1.shape)
print("Array: ", list1)
print ("Dimension: ", list1.ndim)
print ("-----------------------")

# creating a 1-D list (Vertical) 
list2 = [[10], 
        [20], 
        [30]]
list2 = np.array (list2)
print ("Shape: ", list2.shape)
print("Array: ", list2)
print ("Dimension: ", list2.ndim)

Shape:  (3,)
Array:  [1 2 3]
Dimension:  1
-----------------------
Shape:  (3, 1)
Array:  [[10]
 [20]
 [30]]
Dimension:  2


In [120]:
lst1 = [10,20,30,40,50] 
lst2 = [10,20,30,40,50]
 
vctr1 = np.array(lst1) 
 
vctr2= np.array(lst2) 
 
print("Vector created from a list 1:") 
print(vctr1) 
print(vctr1.ndim) 
print("Vector created from a list 2:") 
print(vctr2) 
print(vctr2.ndim) 
 
vctr_div = vctr1/vctr2
print("Division of two vectors: ",vctr_div)
print(vctr_div.ndim) 

Vector created from a list 1:
[10 20 30 40 50]
1
Vector created from a list 2:
[10 20 30 40 50]
1
Division of two vectors:  [1. 1. 1. 1. 1.]
1


### Numpy Vectors

A vector can be considered as a single-dimensional array. With respect to Python, a vector is a one-dimensional array of lists. It occupies the elements in a similar manner as that of a Python list.

In [127]:
## create vector from list

lst = [10,20,30,40,50] 

vctr = np.array(lst) 
print("Vector created from a list:") 
print("Dim: ",vctr.ndim)

Vector created from a list:
Dim:  1


In [128]:
lst = [[2], 
        [4], 
        [6],
          [10]]  

vctr = np.array(lst) 

print("Vector created from a list:") 
print(vctr)
print("Dim: ",vctr.ndim)

Vector created from a list:
[[ 2]
 [ 4]
 [ 6]
 [10]]
Dim:  2


#### With Vectors, following list of the basic operations that can be performed:

* Addition
* Subtraction
* Multiplication
* Division
* Dot Product, etc.

#### Addition

In [137]:
lst1 = [10,20,30,40,50] 
lst2 = [1,2,3,4,5]

vctr1 = np.array(lst1) 
vctr2= np.array(lst2) 

vector_add = vctr1+vctr2
vector_sub = vctr1-vctr2
vector_div = vctr1/vctr2
vector_mul = vctr1*vctr2

vector_dot = np.dot (vctr1, vctr2)

print("Vector1                             : ",vctr1)
print("Vector2                             : ",vctr2)
print("-------------------------------------------------------------")
print("Addition of two vectors             : ",vector_add)
print("Vector dimension (Addition)         : ",vector_add.ndim)
print("-------------------------------------------------------------")
print("Subtraction of two vectors          : ",vector_sub)
print("Vector dimension (Subtraction)      : ",vector_sub.ndim)
print("-------------------------------------------------------------")
print("Division of two vectors             : ",vector_div)
print("Vector dimension (Division)         : ",vector_div.ndim)
print("-------------------------------------------------------------")
print("Multiplication of two vectors       : ",vector_mul)
print("Vector dimension (Multiplication)   : ",vector_mul.ndim)
print("-------------------------------------------------------------")
print("Dot Product of two vectors          : ",vector_dot)
print("Vector dimension (Dot Product)      : ",vector_dot.ndim)

Vector1                             :  [10 20 30 40 50]
Vector2                             :  [1 2 3 4 5]
-------------------------------------------------------------
Addition of two vectors             :  [11 22 33 44 55]
Vector dimension (Addition)         :  1
-------------------------------------------------------------
Subtraction of two vectors          :  [ 9 18 27 36 45]
Vector dimension (Subtraction)      :  1
-------------------------------------------------------------
Division of two vectors             :  [10. 10. 10. 10. 10.]
Vector dimension (Division)         :  1
-------------------------------------------------------------
Multiplication of two vectors       :  [ 10  40  90 160 250]
Vector dimension (Multiplication)   :  1
-------------------------------------------------------------
Dot Product of two vectors          :  550
Vector dimension (Dot Product)      :  0


In [143]:
lst1 = [10,20,30,40,50, 60]

vec_only    = np.array (lst1)
vec_reshape = vec_only.reshape (2, 3) # CORRECT (since this requires 2x3=6 elements)
#vec_reshape = vec_only.reshape (2, 4) # ERROR (since this requires 2x4=8 elements)

### Reshape Functions

numpy.reshape has following synxtax

numpy.reshape(a, /, shape=None, *, newshape=None, order='C', copy=None) where

a        = array_like # array to be reshaped
shape    = int or tuple of ints
newshape = int or tuple of ints

In [144]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [145]:
b = np.reshape(a, (2, 3)) # C-like index ordering
b

array([[0, 1, 2],
       [3, 4, 5]])

In [146]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [147]:
## You are allowed to have one "unknown" dimension.
## Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
## Pass -1 as the value, and NumPy will calculate this number for you.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [148]:
## flatten an array

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [154]:
rng = np.random.default_rng()
results = rng.integers(0, 100, size=(5, 10))
print (results)
print (results.shape)
print (results.shape[0])
print (results.shape[1])
print (results.ndim)

[[91 27 90 72 83 58 10  0  7 94]
 [24 87 64 43 39  5 26 12 65 37]
 [84 45 48 40 34 38 92 16 11 48]
 [ 7 98 85 12  1 32 96 26 14  6]
 [76 30 32 10  8 86 64 52 67 56]]
(5, 10)
5
10
2
